events { worker_connections 1024; }

http {
  upstream product_service     { server product-service:3001; }
  upstream cart_service        { server cart-service:3002; }
  upstream payment_service     { server payment-service:3003; }
  upstream notification_service { server notification-service:3004; }

  server {
    listen 8080;

  # Serve the frontend files from /usr/share/nginx/html
    location / {
      root /usr/share/nginx/html;
      index index.html index.htm;
      try_files $uri $uri/ /index.html; 
    }

    location /products      { proxy_pass http://product_service; }
    location /cart          { proxy_pass http://cart_service; }
    location /payments      { proxy_pass http://payment_service; }
    location /orders        { proxy_pass http://payment_service; }
    location /notify        { proxy_pass http://notification_service; }
    location /notifications { proxy_pass http://notification_service; }

    location /health {
      return 200 '{"status":"gateway ok"}';
      add_header Content-Type application/json;
    }
  }
}